# Generated by Django 5.2 on 2025-08-05 06:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='BeverageDetail',
            new_name='Beverage',
        ),
        migrations.RenameModel(
            old_name='CleanerDetail',
            new_name='Cleaner',
        ),
    ]
