# Generated by Django 6.0 on 2026-03-13 03:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="role",
            field=models.CharField(
                choices=[
                    ("admin", "Admin"),
                    ("beverage_manager", "Beverage Manager"),
                    ("bartender", "Bartender"),
                    ("chef", "Chef"),
                ],
                default="bartender",
                max_length=20,
            ),
        ),
    ]
