# Generated by Django 5.2 on 2025-08-08 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_rename_beveragedetail_beverage_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='beverage',
            name='product',
        ),
        migrations.RemoveField(
            model_name='cleaner',
            name='product',
        ),
        migrations.RemoveField(
            model_name='beverage',
            name='alcohol_content',
        ),
        migrations.RemoveField(
            model_name='cleaner',
            name='is_toxic',
        ),
        migrations.AddField(
            model_name='beverage',
            name='brand',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='beverage',
            name='category',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='beverage',
            name='name',
            field=models.CharField(default='Unnamed Beverage', max_length=100),
        ),
        migrations.AddField(
            model_name='beverage',
            name='quantity',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='beverage',
            name='unit',
            field=models.CharField(default='unit', max_length=50),
        ),
        migrations.AddField(
            model_name='cleaner',
            name='location',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='cleaner',
            name='name',
            field=models.CharField(default='Unnamed Cleaner', max_length=100),
        ),
        migrations.AddField(
            model_name='cleaner',
            name='quantity',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='cleaner',
            name='unit',
            field=models.CharField(default='unit', max_length=50),
        ),
        migrations.DeleteModel(
            name='Product',
        ),
    ]
