# Generated by Django 5.2 on 2025-10-18 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_remove_beverage_product_remove_cleaner_product_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='beverage',
            name='min_stock',
            field=models.PositiveIntegerField(default=10),
        ),
    ]
